package hr.performancemanagement.utils.enums;

public enum ApprovalStatus {
    NEW, PENDING_APPROVAL, APPROVED_BY_SUPERVISOR,  REJECTED_BY_SUPERVISOR, APPROVED_BY_HR, REJECTED_BY_HR, SCORED_BY_EMPLOYEE, SCORED_BY_SUPERVISOR, AGREED_BY_TWO, MODERATED_BY_HR, CLOSED
}
