package hr.performancemanagement.utils.constants;

public class PMConstants {

    public static final String ACTIVITY_CAPTURE_TARGETS = "CAPTURE_TARGETS";
    public static final String ACTIVITY_CAPTURE_EMPLOYEE_SCORES = "ACTIVITY_CAPTURE_EMPLOYEE_SCORES";
    public static final String ACTIVITY_CAPTURE_MANAGER_SCORES = "ACTIVITY_CAPTURE_MANAGER_SCORES";
    public static final String ACTIVITY_CAPTURE_AGREED_SCORES = "ACTIVITY_CAPTURE_AGREED_SCORES";
    public static final String ACTIVITY_CAPTURE_MODERATED_SCORES = "ACTIVITY_CAPTURE_MODERATED_SCORES";
    public static final String ACTIVITY_APPROVE_OWNER_SCORES = "ACTIVITY_APPROVE_OWNER_SCORES";
    public static final String ACTIVITY_APPROVE_AGREED_SCORES = "ACTIVITY_APPROVE_AGREED_SCORES";
    public static final String ACTIVITY_APPROVE_SCORECARD = "ACTIVITY_APPROVE_SCORECARD";
    public static final String ACTIVITY_CLOSE_SCORECARD = "ACTIVITY_CLOSE_SCORECARD";

    public static final String LOCK_STATUS_OPEN = "OPEN";
    public static final String LOCK_STATUS_LOCKED = "LOCKED";
    public static final String LOCK_STATUS_CLOSED = "CLOSED";

    public static final String STATUS_ACTIVE = "ACTIVE";
    public static final String STATUS_IN_ACTIVE = "IN_ACTIVE";
    public static final String REPORTING_DATE_STATUS_OPEN = "OPEN";
    public static final String REPORTING_DATE_STATUS_CLOSED = "CLOSED";
    public static final String REPORTING_ACTIVITY_TARGET_CAPTURE = "TARGET_CAPTURE";
    public static final String REPORTING_ACTIVITY_SCORE_CAPTURE = "SCORE_CAPTURE";
    public static final String REPORTING_ACTIVITY_MODERATION = "MODERATION";
    public static final String REPORTING_ACTIVITY_SCHEDULED = "SCHEDULED";
    public static final String REPORTING_ACTIVITY_BETWEEN_PERIODS = "BETWEEN_PERIODS";
    public static final String REPORTING_ACTIVITY_COMPLETED = "COMPLETED";

    public static final String APPROVAL_STATUS_NEW = "NEW";
    public static final String APPROVAL_STATUS_PENDING_APPROVAL = "PENDING_APPROVAL";
    public static final String APPROVAL_STATUS_APPROVED_BY_SUPERVISOR = "APPROVED_BY_SUPERVISOR";
    public static final String APPROVAL_STATUS_REJECTED_BY_SUPERVISOR = "REJECTED_BY_SUPERVISOR";
    public static final String APPROVAL_STATUS_APPROVED_BY_HR = "APPROVED_BY_HR";
    public static final String APPROVAL_STATUS_REJECTED_BY_HR = "REJECTED_BY_HR";
    public static final String APPROVAL_STATUS_SCORED_BY_EMPLOYEE = "SCORED_BY_EMPLOYEE";
    public static final String APPROVAL_STATUS_APPROVED_OWNER_SCORES = "APPROVED_OWNER_SCORES";
    public static final String APPROVAL_STATUS_REJECTED_OWNER_SCORES = "REJECTED_OWNER_SCORES";
    public static final String APPROVAL_STATUS_SCORED_BY_SUPERVISOR = "SCORED_BY_SUPERVISOR";
    public static final String APPROVAL_STATUS_AGREED_BY_TWO = "AGREED_BY_TWO";
    public static final String APPROVAL_STATUS_APPROVED_AGREED_SCORES = "APPROVED_AGREED_SCORES";
    public static final String APPROVAL_STATUS_MODERATED_BY_HR = "MODERATED_BY_HR";
    public static final String APPROVAL_STATUS_CLOSED = "CLOSED";

    public static final String HAS_SPECIAL_RIGHTS = "HAS_SPECIAL_RIGHTS";
    public static final String HAS_NO_SPECIAL_RIGHTS = "HAS_NO_SPECIAL_RIGHTS";
    public static final String IS_ADMIN = "IS_ADMIN";
    public static final String IS_NOT_ADMIN = "IS_NOT_ADMIN";

    public static final String MODERATOR = "MODERATOR";
    public static final String STANDARD_SCORECARD = "STANDARD_SCORECARD";
    public static final String VALUE_BASED = "VALUE_BASED";
    public static final String USER_TYPE_OWNER = "OWNER";
    public static final String USER_TYPE_SUPERVISOR = "SUPERVISOR";
    public static final String USER_TYPE_MODERATOR = "MODERATOR";

    public static final String TASK_STATUS_OPEN = "OPEN";
    public static final String TASK_STATUS_COMPLETED = "COMPLETED";
    public static final String PIP_STATUS_TODO = "todo";
    public static final String PIP_STATUS_NOT_APPLICABLE = "NOT_APPLICABLE";
    public static final String PIP_SOURCE_SELF_ASSESSMENT = "SELF_ASSESSMENT";

    public static final String PROBATION_STATUS_DRAFT = "DRAFT";
    public static final String PROBATION_STATUS_PENDING = "PENDING";
    public static final String PROBATION_STATUS_AUTHORIZED = "AUTHORIZED";
    public static final String PROBATION_STATUS_REJECTED = "REJECTED";
    public static final String PROBATION_STATUS_CONTRACT_CREATED = "CONTRACT_CREATED";
    public static final String PROBATION_STATUS_KPI_SET = "KPI_SET";
    public static final String PROBATION_STATUS_KPI_PENDING_SUPERVISOR_APPROVAL = "KPI_PENDING_SUPERVISOR_APPROVAL";
    public static final String PROBATION_STATUS_KPI_PENDING_HR_APPROVAL = "KPI_PENDING_HR_APPROVAL";
    public static final String PROBATION_STATUS_KPI_APPROVED = "KPI_APPROVED";
    public static final String PROBATION_STATUS_KPI_REJECTED_BY_SUPERVISOR = "KPI_REJECTED_BY_SUPERVISOR";
    public static final String PROBATION_STATUS_KPI_REJECTED_BY_HR = "KPI_REJECTED_BY_HR";
    public static final String PROBATION_STATUS_EVALUATION_IN_PROGRESS = "EVALUATION_IN_PROGRESS"; // New status
    public static final String PROBATION_STATUS_EVALUATION_PENDING_SUPERVISOR_REVIEW = "EVALUATION_PENDING_SUPERVISOR_REVIEW"; // New status
    public static final String PROBATION_STATUS_PERSONAL_DIMENSIONS_IN_PROGRESS = "PERSONAL_DIMENSIONS_IN_PROGRESS";
    public static final String PROBATION_STATUS_EVALUATION_PENDING_HR_APPROVAL = "EVALUATION_PENDING_HR_APPROVAL"; // New status
    public static final String PROBATION_STATUS_EVALUATION_COMPLETED = "EVALUATION_COMPLETED"; // New status
    public static final String PROBATION_STATUS_EVALUATION_REJECTED_BY_SUPERVISOR = "EVALUATION_REJECTED_BY_SUPERVISOR"; // New status
    public static final String PROBATION_STATUS_EVALUATION_REJECTED_BY_HR = "EVALUATION_REJECTED_BY_HR"; // New status


    public static final String PROBATION_ACTION_SUBMITTED = "SUBMITTED";
    public static final String PROBATION_ACTION_APPROVED = "APPROVED";
    public static final String PROBATION_ACTION_REJECTED = "REJECTED";

    public static final String PROBATION_APPROVER_MODE_SUPERVISOR = "SUPERVISOR";
    public static final String PROBATION_APPROVER_MODE_ACCOUNT_TYPE = "ACCOUNT_TYPE";
    public static final String PROBATION_APPROVER_MODE_ROLE = "ROLE";
    public static final String PROBATION_APPROVER_MODE_USER = "USER";

    public static final String SCORECARD_WORKFLOW_ROLE_NEW = "NEW";
    public static final String SCORECARD_WORKFLOW_ROLE_NONE = "NONE";
    public static final String SCORECARD_WORKFLOW_ROLE_PENDING_APPROVAL = "PENDING_APPROVAL";
    public static final String SCORECARD_WORKFLOW_ROLE_APPROVED_BY_SUPERVISOR = "APPROVED_BY_SUPERVISOR";
    public static final String SCORECARD_WORKFLOW_ROLE_REJECTED_BY_SUPERVISOR = "REJECTED_BY_SUPERVISOR";
    public static final String SCORECARD_WORKFLOW_ROLE_APPROVED_BY_HR = "APPROVED_BY_HR";
    public static final String SCORECARD_WORKFLOW_ROLE_REJECTED_BY_HR = "REJECTED_BY_HR";
    public static final String SCORECARD_WORKFLOW_ROLE_SCORED_BY_EMPLOYEE = "SCORED_BY_EMPLOYEE";
    public static final String SCORECARD_WORKFLOW_ROLE_APPROVED_OWNER_SCORES = "APPROVED_OWNER_SCORES";
    public static final String SCORECARD_WORKFLOW_ROLE_SCORED_BY_SUPERVISOR = "SCORED_BY_SUPERVISOR";
    public static final String SCORECARD_WORKFLOW_ROLE_AGREED_BY_TWO = "AGREED_BY_TWO";
    public static final String SCORECARD_WORKFLOW_ROLE_APPROVED_AGREED_SCORES = "APPROVED_AGREED_SCORES";
    public static final String SCORECARD_WORKFLOW_ROLE_MODERATED_BY_HR = "MODERATED_BY_HR";
    public static final String SCORECARD_WORKFLOW_ROLE_CLOSED = "CLOSED";

    public static final String SCORECARD_STAGE_NEW = "SCORECARD_STAGE_NEW";
    public static final String SCORECARD_STAGE_CAPTURE_TARGETS = "SCORECARD_STAGE_CAPTURE_TARGETS";
    public static final String SCORECARD_STAGE_TARGETS_APPROVAL_BY_SUPERVISOR = "SCORECARD_STAGE_TARGETS_APPROVAL_BY_SUPERVISOR";
    public static final String SCORECARD_STAGE_TARGETS_APPROVAL_BY_HR = "SCORECARD_STAGE_TARGETS_APPROVAL_BY_HR";
    public static final String SCORECARD_STAGE_OWNER_SCORING = "SCORECARD_STAGE_OWNER_SCORING";
    public static final String SCORECARD_STAGE_OWNER_SCORE_APPROVAL = "SCORECARD_STAGE_OWNER_SCORE_APPROVAL";
    public static final String SCORECARD_STAGE_SUPERVISOR_SCORING = "SCORECARD_STAGE_SUPERVISOR_SCORING";
    public static final String SCORECARD_STAGE_AGREED_SCORE_CAPTURING = "SCORECARD_STAGE_AGREED_SCORE_CAPTURING";
    public static final String SCORECARD_STAGE_AGREED_SCORE_APPROVAL = "SCORECARD_STAGE_AGREED_SCORE_APPROVAL";
    public static final String SCORECARD_STAGE_MODERATOR_SCORE_CAPTURING = "SCORECARD_STAGE_MODERATOR_SCORE_CAPTURING";
    public static final String SCORECARD_STAGE_CLOSED = "SCORECARD_STAGE_CLOSED";

}
